title: Harinadh Jakka # your name (or website title) here
logo: "images/My LinkedIn DP 1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 As a data professional with valuable expertise in the Data Analytics field, I dive into data, uncover patterns, and provide valuable insights through analysis and visualization, empowering informed decision-making 📊 <br><br>
  I love reading fiction, traveling and playing badminton <br><br>
  <a href="https://www.linkedin.com/in/jakkaharinadh/">View My LinkedIn Profile</a> <br><br>
   <a href="https://public.tableau.com/app/profile/harinadh.jakka">View My Tableau work</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
